#! /bin/sh

sxhkd &

##bspc monitor -d TERM MUSIC WEB FILES DEV
##bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 一 二 三 四 五 六 七

bspc rule -a URxvt state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config focus_follows_pointer true
bspc config border_width         3
bspc config border_radius         12
bspc config window_gap           15
bspc config focused_border_color "#FFDAB9"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
sh .fehbg
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr &
# Make betterlockscreen generate and cache a background image for locking
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# ------- Autostart apps ------
# Picom
picom -b &
##picom --glx-sync-fence &
# Dunst
dunst &
# Dropbox
dropbox &
nm-applet &
# cmst &
pamac-tray &
##volumeicon &
redshift-gtk -l 11.23:75.78 


# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
libinput-gestures-setup start
# Xinput configs (touchpad)
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0
# ------- Keyboard fixes ------
# Remap Caps-lock key to Escape, for using VIM
#setxkbmap -option caps:escape
# Make US and DK keyboard layout togglable with Shift+Alt
#setxkbmap -layout us,dk -option grp:alt_shift_toggle
exec ksuperkey -e 'Super_L=Super_L|d' &

