#! /bin/sh

sxhkd &

##bspc monitor -d TERM MUSIC WEB FILES DEV
##bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 一 二 三 四 五 六 七

bspc rule -a Alacritty state=floating 
bspc rule -a Plank layer=above manage=on border=off
bspc rule -a "MEGAsync" state=floating follow=on

bspc config focus_follows_pointer true

bspc config border_width          5 
bspc config window_gap            6
bspc config top_padding           28
bspc config left_padding          0
bspc config right_padding         0
bspc config bottom_padding        0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true


bspc config focused_border_color "#80cfa3"
bspc config active_border_color  "#80cfa3"
bspc config normal_border_color  "#f79925"

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
sh .fehbg
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr &
# Make betterlockscreen generate and cache a background image for locking
xss-lock -- lock.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xbacklight -set 50 &
# ------- Autostart apps ------
# Picom
picom -b &
##picom --glx-sync-fence &
# Dunst
dunst &
tail -f /tmp/volumepipe | xob &
# Dropbox
##dropbox &
nm-applet &
# cmst &
mpd &
##volumeicon &
redshift-gtk -l 11.23:75.78 &
mpd-discord-rpc &
start-mpd-notif.sh 


# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
libinput-gestures-setup start
# Xinput configs (touchpad)
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Click Method Enabled" 0 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled" 0
xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Locked Drags" 1
#Xinput configs(mouse)
#xinput set-prop 9 "libinput Scroll Method Enabled" 0, 0, 1 

# ------- Keyboard fixes ------
# Remap Caps-lock key to Escape, for using VIM
#setxkbmap -option caps:escape
# Make US and DK keyboard layout togglable with Shift+Alt
#setxkbmap -layout us,dk -option grp:alt_shift_toggle
##exec ksuperkey -e 'Super_L=Super_L|d' &

