#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload


# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-q close
hc keybind $Mod-Return spawn alacritty
hc keybind $Mod-d spawn dmenu_run
hc keybind XF86AudioRaiseVolume spawn sh -c "amixer -D pipewire set Master 5%+  && voldunst"
hc keybind XF86AudioLowerVolume spawn sh -c "amixer -D pipewire set Master 5%-  && voldunst"
hc keybind XF86AudioMute spawn sh -c "amixer -D pipewire set Master toggle"
hc keybind XF86MonBrightnessUp spawn sh -c "light -A 5 && bridunst"
hc keybind XF86MonBrightnessDown spawn sh -c "light -U 5 && bridunst"
hc keybind $Mod-XF86AudioStop spawn powermenu.sh
hc keybind $Mod-w spawn jumpapp firefox
hc keybind XF86TouchpadOff spawn sh -c "xinput disable 'Elan Touchpad'"
hc keybind XF86TouchpadOn spawn sh -c "xinput enable 'Elan Touchpad'"
hc keybind XF86AudioPlay spawn sh -c "playerctl play-pause"
hc keybind XF86AudioNext spawn sh -c "playerctl next"
hc keybind XF86AudioPrev spawn sh -c "playerctl previous"
hc keybind $Mod-XF86AudioPlay spawn sh -c "mpc toggle"
hc keybind $Mod-XF86AudioPrev spawn sh -c "mpc prev"
hc keybind $Mod-XF86AudioNext spawn sh -c "mpc next"
hc keybind $Mod-e spawn jumpapp thunar
hc keybind $Mod-r spawn alacritty -e ranger
hc keybind $Mod-Shift-a spawn alacritty -e btm
hc keybind Print spawn sh -c "maim ~/Pictures/Screenshots/$(date +%s).png && notify-send \"Maim\" \"Screenshot Captured\""
hc keybind Shift-Print spawn sh -c "maim -s -o | xclip -selection clipboard -t image/png"
# basic movement in tiling and floating mode
# focusing clients
hc set focus_follows_mouse true
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep
hc keybind $Mod-z cycle_value frame_border_width 0 3

# tags
tag_names=( {1..5} )
tag_keys=( {1..5}  )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-x remove
hc keybind $Mod-s spawn sh -c "herbstclient floating toggle && .config/herbstluftwm/switch-panel-static"
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-s set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-t set_attr clients.focus.tiling toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Shift-d attr clients.focus.decorated toggle
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
hc set default_frame_layout 1
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
    or , and . compare tags.focus.curframe_wcount = 2                   \
    . cycle_layout +1 vertical horizontal max vertical grid    \
    , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr tabbed_max 1
hc set theme.title_when 'multiple_tabs'
hc set frame_border_active_color '#f2dde6'
hc set frame_border_normal_color '#fcf7f9'
hc set frame_bg_normal_color '#fcf7f9'
hc set frame_bg_active_color '#f2dde6'
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 20
hc set snap_gap 8
hc set snap_distance 10
hc set frame_normal_opacity 100

hc keybind $Mod-g cycle_value frame_gap 0 20

hc attr theme.title_height 30
hc attr theme.title_depth 10
hc attr theme.title_font 'Apple Garamond:size=13'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.padding_top 0  # space below the title's baseline (i.e. text depth)
hc attr theme.floating.padding_top 40
hc attr theme.title_color '#2A2424'
hc attr theme.normal.title_color '#2A2424'
hc attr theme.border_width 15
hc attr theme.inner_width 5
hc attr theme.outer_width 5
hc attr theme.inner_color '#fcf7f9'
hc attr theme.outer_color '#fcf7f9'
hc attr theme.color '#f2dde6'
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 0
hc attr theme.floating.inner_width 0
hc attr theme.floating.outer_color '#fcf7f9'
hc attr theme.floating.inner_color '#fcf7f9'
hc attr theme.floating.color '#f2dde6'
hc attr theme.normal.inner_color '#fcf7f9'
hc attr theme.tab_color '#fcf7f9'
hc attr theme.title_align center
hc attr theme.title_when multiple_tabs
hc attr theme.background_color '#f2dde6'

hc set window_gap 10
hc set frame_padding 10
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=Alacritty floating=on floatplacement=center
hc rule class=Thunar floating=on floatplacement=center
hc rule class=feh floating=on floatplacement=center

hc set tree_style '╾│ ├└╼─┐'


# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
sh .fehbg &
#hsetroot -solid '#f8f7fc' &
xss-lock -l -- /home/mio/.local/bin/lock.sh &
xrdb ~/.Xresources &
picom  &
#/home/mio/.config/herbstluftwm/switch-panel.sh &
eww open bar &
dunst &
redshift &
spotifyd &
